-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "ADMIN" SALT 'c2e757c7fcb8b0e7' HASH '25aeb78390e68f76c88a5a4c5d3cd369d59f7f7dd81b2dd9e55ed89acf93739d' ADMIN;      
CREATE SEQUENCE "PUBLIC"."ACCOUNT_CASH_SEQ" START WITH 1 INCREMENT BY 50;     
CREATE SEQUENCE "PUBLIC"."ACCOUNT_SEQ" START WITH 1 INCREMENT BY 50;          
CREATE SEQUENCE "PUBLIC"."MERCHANT_SEQ" START WITH 1 INCREMENT BY 50;         
CREATE MEMORY TABLE "PUBLIC"."ACCOUNT"(
    "CASH_QT" FLOAT(53),
    "ACCOUNT_ID" BIGINT NOT NULL,
    "HOLDER_NAME" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."ACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ACCOUNT_ID");              
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT; 
INSERT INTO "PUBLIC"."ACCOUNT" VALUES
(100.0, 1, 'Joao Rodrigues'),
(200.0, 2, 'Antonio Magri');            
CREATE MEMORY TABLE "PUBLIC"."ACCOUNT_CASH"(
    "CASH_QT" FLOAT(53),
    "ACCOUNT_CASH_ID" BIGINT NOT NULL,
    "ACCOUNT_ID" BIGINT,
    "CATEGORY_ID" BIGINT
);        
ALTER TABLE "PUBLIC"."ACCOUNT_CASH" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ACCOUNT_CASH_ID");    
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_CASH;            
INSERT INTO "PUBLIC"."ACCOUNT_CASH" VALUES
(120.0, 0, 1, 1),
(220.0, 1, 2, 0),
(320.5, 2, 2, 1);           
CREATE MEMORY TABLE "PUBLIC"."CATEGORY"(
    "CATEGORY_ID" BIGINT NOT NULL,
    "CATEGORY_NAME" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("CATEGORY_ID");            
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORY;
INSERT INTO "PUBLIC"."CATEGORY" VALUES
(0, 'MEAL'),
(1, 'FOOD');            
CREATE MEMORY TABLE "PUBLIC"."MERCHANT"(
    "MERCHANT_ID" BIGINT NOT NULL,
    "MERCHANT_NAME" CHARACTER VARYING(255),
    "CATEGORY_ID" BIGINT
);       
ALTER TABLE "PUBLIC"."MERCHANT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("MERCHANT_ID");            
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.MERCHANT;
INSERT INTO "PUBLIC"."MERCHANT" VALUES
(0, 'MEAL                        SAO PAULO BR', 0),
(1, 'FOOD                        SAO PAULO BR', 1),
(2, 'CASH                        SAO PAULO BR', NULL);      
ALTER TABLE "PUBLIC"."MERCHANT" ADD CONSTRAINT "PUBLIC"."FKJOXQJ4U1MY4FX3QFI3QE25CPA" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("CATEGORY_ID") NOCHECK;       
ALTER TABLE "PUBLIC"."ACCOUNT_CASH" ADD CONSTRAINT "PUBLIC"."FKK2A1COVXVFJ32N7OB1G04T9XI" FOREIGN KEY("ACCOUNT_ID") REFERENCES "PUBLIC"."ACCOUNT"("ACCOUNT_ID") NOCHECK;      
ALTER TABLE "PUBLIC"."ACCOUNT_CASH" ADD CONSTRAINT "PUBLIC"."FKLSFUO7AXCHBACWA1QH9GWKIJ9" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("CATEGORY_ID") NOCHECK;   
